# Site settings
title: Cult - a clean Jekyll theme for your blog
description: "Cult is a clean, minimal, ready to use Jekyll template for your blog"
url: "http://claudiuconstantin.github.io/cult"
author:
  name: "Claudiu Constantin"
  email: "claudiu@fastmail.com"
  url: "http://claudiuconstantin.com/"

# Build settings
markdown: kramdown
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
plugins:
  - jekyll-feed
  - jekyll-paginate

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
theme-name: "Cult"

# Options
previous_next_links: false
custom_header: false
custom_nav_footer: false
reverse: false
